#!/bin/bash

[ $# -ge 1 -a -f "$1" ] && input="$1" || input="-"

color_code_regex=$'(\x1B\\[([0-9]{1,2}(;[0-9]{1,2})?)[m|K])?'
reset_color="\x1B\[m"
dim_magenta="\x1B\[38;05;146m"

format_diff_header () {
	# simplify the unified patch diff header
	sed -E "s/^($color_code_regex)diff --git .*$//g" | \
	sed -E "s/^($color_code_regex)index .*$/\
\1$(print_horizontal_rule)/g" | \
	sed -E "s/^($color_code_regex)\+\+\+(.*)$/\1\+\+\+\5\\
\1$(print_horizontal_rule)/g"
}

colorize_context_line () {
	# extra color for @@ context line
	sed -E "s/@@$reset_color $reset_color(.*$)/@@ $dim_magenta\1/g"
}

strip_leading_symbols () {
	# strip the + and -
	sed -E "s/^($color_code_regex)[\+\-]/\1 /g"
}

print_horizontal_rule () {
	printf "%$(tput cols)s\n"|sed 's/ /─/g'
}

# run it.
cat $input | format_diff_header |  colorize_context_line | strip_leading_symbols
